# 2 Practice and Comprehensive Questions Solutions

In [ ]:
import numpy as np
import numpy.random as random
import numpy.linalg as LA

# Display up to 3 decimal places
%precision 3

'%.3f'

In [2]:
URL = "https://www.ncei.noaa.gov/pub/data/cdo/samples/GHCND_sample_csv.csv"

raw = np.loadtxt(URL, delimiter=",", usecols=[6,7,8], skiprows=1)

jan_tmax = raw[0:31, 0]
jan_tmin = raw[0:31, 1]
jan_prcp = raw[0:31, 2]
jan_tmax = jan_tmax / 10
jan_tmin = jan_tmin / 10
jan_prcp = jan_prcp / 10

X = raw / 10

In [3]:
X

array([[-1.780e+01, -3.110e+01,  0.000e+00],
       [-2.440e+01, -3.220e+01,  0.000e+00],
       [-1.940e+01, -2.890e+01,  0.000e+00],
       [-1.670e+01, -2.000e+01,  1.500e+00],
       [-1.330e+01, -1.670e+01,  9.999e+02],
       [-1.330e+01, -1.720e+01,  9.999e+02],
       [-1.500e+01, -2.780e+01,  0.000e+00],
       [-2.330e+01, -3.280e+01,  0.000e+00],
       [-2.330e+01, -3.220e+01,  0.000e+00],
       [-1.170e+01, -2.440e+01,  0.000e+00],
       [-6.700e+00, -1.280e+01,  0.000e+00],
       [-7.800e+00, -1.220e+01,  0.000e+00],
       [-1.700e+00, -8.900e+00,  0.000e+00],
       [ 3.900e+00, -7.200e+00,  0.000e+00],
       [-6.700e+00, -7.200e+00,  0.000e+00],
       [ 2.200e+00, -5.000e+00,  0.000e+00],
       [ 3.300e+00, -4.400e+00,  0.000e+00],
       [ 6.000e-01, -1.720e+01,  0.000e+00],
       [-5.600e+00, -1.830e+01,  0.000e+00],
       [-6.700e+00, -1.390e+01,  0.000e+00],
       [-6.700e+00, -9.400e+00,  2.500e+00],
       [-4.400e+00, -6.700e+00,  0.000e+00],
       [-6

### <Practice Question 2-1>

(1) Create two 1-dimenional `np.ndarray` arrays with a length of 3, 1 with even numbers as elements, and 1 with odd numbers as elements. Then use the `type()` function to confirm that they are of type `np.ndarray`.

In [4]:
# (1)
array1 = np.array([0,2,4])
array2 = np.array([1,3,5])

In [5]:
type(array1)

numpy.ndarray

In [6]:
type(array2)

numpy.ndarray

(2) Add the 2 arrays that you created in (1) and confirm that it results in element-wise addition of the 2 arrays.

In [7]:
# (2)
print(array1 + array2)

[1 5 9]


(3) Create a function `normalize(a)` that takes a 1-dimensional array as an argument and outputs a 1-dimensional array where the input is normalized.

Here, normalization of a vector means scaling the original vector so that the square root of the sum of the squares of all its elements, which is called the L2 norm, equals 1.

In this task, please implement the function using only **NumPy's universal operations and functions**.

Hint: Let's try and normalize the vector $v=(1,1,1)$ by hand. The L2 norm of $v$ ,denoted as $||v||_2$, is $||v||_2 = \sqrt{1^2+1^2+1^2}=\sqrt{3}$. If we scale the original vector $v$ by the reciprocal of the L2 norm $\frac{1}{\sqrt{3}}$, we get a new vector $v' = (\frac{1}{\sqrt{3}},\frac{1}{\sqrt{3}},\frac{1}{\sqrt{3}})$. We can confirm that the L2 norm of $v'$ is 1:
 $$||v'|| = \sqrt{(\frac{1}{\sqrt{3}})^2+(\frac{1}{\sqrt{3}})^2+(\frac{1}{\sqrt{3}})^2} = \sqrt{\frac13+\frac13+\frac13}=1$$


In [8]:
# (3)
def normalize(a):
    return a / np.sqrt(np.sum(a**2))

In [9]:
array1

array([0, 2, 4])

In [10]:
print(normalize(array1))
print(np.sqrt(np.sum(normalize(array1)**2)))

[0.    0.447 0.894]
0.9999999999999999


### <Practice Question 2-2>

(1) Using the array `jan_tmax` that we built, create a new array `tmax_mon` that contains the max temperatures of all Mondays in January. As mentioned previously, January 1st is a Friday.

In [11]:
# (1)
tmax_mon = jan_tmax[3::7]

(2) Calculate the average max temperature of all Mondays in January, then calculate the standard deviation of the max temperature of all Mondays in January.

Hint: The formula for the standard deviation $\sigma$ of a given data set is:
$$
\sigma = \sqrt{\frac{\sum (x_i - \mu)^2}{N}}
$$
where $\mu$ is the average value of the data, and $N$ is the size of the dataset.

For example, let's calculate the standard deviation of the 2 datasets:
$$
D_1 = (-5,0,5),\quad D_2 = (-100,0,100)
$$
You can tell that both datasets have the same average value of $0$, but $D_2$ is more "spread out" than $D_1$.The standard deviation of the 2 datasets $\sigma_1$ and $\sigma_2$ are:
$$
\sigma_1 = \sqrt{\frac{(-5-0)^2+(0-0)^2+(5-0)^2}{3}} = 4.08 \\
\sigma_2 = \sqrt{\frac{(-100-0)^2+(0-0)^2+(100-0)^2}{3}} = 81.6
$$
As you can see, the more "spread out" dataset had a higher standard deviation. Therefore, one can say that standard deviation is a measure of how spread out the data points are within a dataset.


You will never have to write out the code for this, as NumPy already has a function `np.std()` that does this for you (you are free to use it in this problem of course!).

In [12]:
# (2)
print("Mean: ", tmax_mon.mean())
print("Standard deviation: ", tmax_mon.std())

Mean:  -5.975
Standard deviation:  6.7555070128007415


### <Practice Question 2-3>

(1) Using the 2-dimensional array `X` we just built, find the mean value and standard deviation for each column (`TMAX`, `TMIN`, `PRCP`), resulting with 2 1-dimensional arrays of length 3.

In [13]:
# (1)
X_means = np.mean(X, axis=0)
X_stds = np.std(X, axis=0)
print("Means: ", X_means)
print("Standard deviations: ", X_stds)

Means:  [-10.168 -18.197  64.639]
Standard deviations:  [  8.296   9.667 245.612]


(2) **Standardize** all elements in `X` with respect to the mean and standard deviation that you calculated in (1), and store the new values in a new array `X_std`. This should result in a 2-dimensional array with a shape of (31,3).

Hint: If a dataset has a mean of $\mu$ and a standard deviation of $\sigma$, to standardize a data point $x$ means to perform the transformation:  
$$
z = \frac{x - \mu}{\sigma}
$$
where $z$ is the standardized version of the original data point (or the "**z-score**"). Therefore, you are going to perform this transformation on all of the elements in `X` in this problem.

For example, the data set $-5,0,5$ has a mean value of $0$ and a standard deviation of $4.08$, so performing this transformation would result in a data set of$-1.2,0,1.2$.

**Standardization** is used very frequently in statistics and machine learning, and we will use it later in this course as well. Whenever you have multiple variables in a dataset (such as `TMAX`,`TMIN`,`PRCP`) with different scales or units, standardization forces them to have the exact same scale, making the data more consistent and easier to deal with.

In [14]:
# (2)
X_std = (X - X_means) / X_stds
X_std.shape

(31, 3)

### <Practice Question 2-4>

(1) Implement a function `get_data_zscore(date)` that takes an integer `date` (from 4 to 28) representing a day in January.

The function should:

1. Retrieve the `TMAX`,`TMIN`,`PCRP` of the days within 3 days of `date` (e.g., for January 5th, retrieve January 2nd through January 8th).
2. Calculate and return the z-score (exactly like you did in Practice Question 2-3!) of the target day's `TMAX`,`TMIN`,`PCRP` relative to that 7-day window. This should result in a 1-dimensional array with a length of 3.

In [15]:
# (1)
def get_data_zscore(date):
  means = np.mean(X[date-4:date+3])
  stds = np.std(X[date-4:date+3])
  answer = (X[date] - means) / stds
  return answer

get_data_zscore(4)

array([-0.317, -0.329,  3.08 ])

(2) Using boolean indexing that you just learned, calculate the average max temperature of all days with no rain, and of all days with rain (make sure to exclude days with a missing value `PCRP` value).

In [16]:
# (2)
mask_no_rain = X[:,2] == 0
mask_rain = (X[:,2] != 0) & (X[:,2] != 99.99)
no_rain_mean = np.mean(X[mask_no_rain,0])
rain_mean = np.mean(X[mask_rain,0])

print("Average tmax of days with no rain: ", no_rain_mean)
print("Average tmax of days with rain: ", rain_mean)

Average tmax of days with no rain:  -9.822222222222221
Average tmax of days with rain:  -12.5


***

## 2.7 Comprehensive Question

**Question 1**\
Recently, in natural language processing using deep learning, models based on Google’s Transformer have gained attention due to their human-level performance on several NLP tasks.

In January 2020, Google introduced [Reformer](https://arxiv.org/abs/2001.04451), which improves the time and space complexity of the Transformer model. In this task, we will implement a part of the Reformer paper, which uses [*cross-polytope LSH*](https://arxiv.org/abs/1509.02897) to improve the time complexity of the Transformer, with guided instructions.

Consider the following question:
>Given $n$ vectors, we want to assign the same integer value to "similar" vectors and different integer values to "dissimilar" vectors. In this context, "similar" vectors are those whose angle is close to 0.


The challenges of this problem are as follows:
- How small should the angle be for vectors to be considered "similar"?
- Even if vectors $a$ and $b$, and  $b$ and $c$ are "similar", $a$ and $c$ may not necessarily be considered "similar."
- To compute the angle $\theta$, we can use their inner product and norms to calculate $\cos \theta$. We could then sort this value and assign integers accordingly, but sorting can become slow as $n$ increases (since the number of combinations of vectors is $_nC_2 = O(n^2)$).

We consider the following probablistic approach:

1. Rotate all vectors by the same random angle.

2. Vectors that are "similar" will, with **high probability**, remain in the same quadrant after rotation, while vectors that are "dissimilar" will, with **high probability**, end up in different quadrants.

3. Therefore, by assigning each vector an integer value corresponding to the quadrant it belongs to after the random rotation, the problem can be solved with **high probability**.

Let's implement this approach.



This time, we consider 100 3D row vectors.

In [17]:
A = random.randn(100, 3) # A matrix stacked with 100 3D row vectors
print(A)

[[ 1.35   0.567 -1.294]
 [ 0.997  0.537 -0.908]
 [-0.347 -0.252 -1.698]
 [-0.157  1.829 -0.427]
 [ 1.143  1.938  1.889]
 [-0.191  0.322 -1.377]
 [-0.166  1.361 -1.238]
 [ 0.534 -1.663  2.017]
 [-0.387  1.882  0.498]
 [ 0.897 -1.08  -0.528]
 [-0.733  0.561  1.756]
 [ 0.621 -0.03   0.038]
 [ 1.163  0.723  1.367]
 [ 1.179 -0.161  0.32 ]
 [-0.137  0.013  0.211]
 [-0.022 -0.935  0.165]
 [ 0.061 -1.446 -0.542]
 [-0.629  0.632  0.795]
 [-1.536 -1.579  0.769]
 [-1.63  -2.331 -0.372]
 [ 0.574 -0.263 -0.359]
 [-0.115  0.465  0.429]
 [-0.594 -1.103  0.891]
 [ 0.925  0.161  1.187]
 [-0.597  1.217  0.233]
 [-0.989  1.093  1.772]
 [-0.689 -1.314 -0.715]
 [ 0.659  0.414  1.01 ]
 [ 0.213  2.047  0.227]
 [ 0.56  -0.697  2.328]
 [ 1.427 -0.717  0.965]
 [ 0.589  0.857  1.14 ]
 [ 0.276  0.328  0.356]
 [-0.674  0.914 -0.207]
 [-1.202 -0.052 -0.251]
 [ 1.028 -0.336 -0.797]
 [ 0.407 -0.691 -0.598]
 [-0.511  0.421 -0.927]
 [ 0.687  0.818  2.139]
 [ 0.595  1.216 -0.257]
 [-0.026 -0.557 -0.984]
 [-0.012  0.902 

(1) Generate a rotation matrix $R$ that rotates 100 vectors, and compute the matrix of rotated vectors stacked vertically into a shape of (100, 3). Here, the 3D rotation matrix $R$ for a random rotation is generated by passing a 1D array of three randomly generated angle parameters to the `gen_R_3d` function.

In [18]:
# (1)
def gen_R_3d(p):
    px, py, pz = p
    Rx = np.array([
        [1, 0, 0],
        [0, np.cos(px), np.sin(px)],
        [0, -np.sin(px), np.cos(px)]
    ])
    Ry = np.array([
        [np.cos(py), 0, -np.sin(py)],
        [0, 1, 0],
        [np.sin(py), 0, np.cos(py)]
    ])
    Rz = np.array([
        [np.cos(pz), np.sin(pz), 0],
        [-np.sin(pz), np.cos(pz), 0],
        [0, 0, 1]
    ])

    return Rz @ Ry @ Rx

p =  2 * np.pi * random.rand(3)
R = gen_R_3d(p)

B = (R @ A.T).T
print(B)

[[ 1.430e+00 -1.101e+00  7.495e-01]
 [ 1.034e+00 -9.053e-01  4.682e-01]
 [-7.452e-02 -3.728e-01  1.710e+00]
 [-3.338e-01 -1.841e+00 -2.294e-01]
 [ 6.093e-01 -1.174e+00 -2.623e+00]
 [-4.001e-02 -7.958e-01  1.184e+00]
 [-1.703e-01 -1.708e+00  6.829e-01]
 [ 4.635e-01  2.251e+00 -1.356e+00]
 [-6.942e-01 -1.530e+00 -1.057e+00]
 [ 1.094e+00  7.404e-01  7.099e-01]
 [-1.034e+00  1.844e-01 -1.683e+00]
 [ 6.085e-01 -2.375e-03 -1.334e-01]
 [ 8.594e-01 -2.445e-01 -1.716e+00]
 [ 1.134e+00  1.841e-01 -4.445e-01]
 [-1.649e-01  7.569e-02 -1.739e-01]
 [ 7.734e-02  9.285e-01  1.838e-01]
 [ 3.226e-01  1.133e+00  1.000e+00]
 [-8.098e-01 -2.456e-01 -8.432e-01]
 [-1.408e+00  1.857e+00  1.240e-01]
 [-1.245e+00  2.135e+00  1.455e+00]
 [ 6.473e-01  6.956e-02  3.218e-01]
 [-2.328e-01 -2.630e-01 -5.388e-01]
 [-5.622e-01  1.394e+00 -3.219e-01]
 [ 7.239e-01  2.263e-01 -1.310e+00]
 [-7.769e-01 -9.977e-01 -5.405e-01]
 [-1.358e+00 -2.838e-01 -1.841e+00]
 [-4.063e-01  1.000e+00  1.244e+00]
 [ 4.539e-01 -5.502e-02 -1.1

(2) To normalize each vector obtained in (1) so that the L2 norm equals 1 and then stack them vertically to form a (100, 3) matrix, you would follow these steps:

Compute the L2 norm for each vector.
Normalize each vector by dividing by its L2 norm.
Stack the normalized vectors without changing their order.

In [19]:
# (2)
B_norm_l2 = LA.norm(B, ord=2, axis=1, keepdims=True)
B_normalized = B / B_norm_l2
print(B_normalized)

[[ 0.732 -0.564  0.384]
 [ 0.712 -0.624  0.323]
 [-0.043 -0.213  0.976]
 [-0.177 -0.977 -0.122]
 [ 0.207 -0.4   -0.893]
 [-0.028 -0.558  0.83 ]
 [-0.092 -0.925  0.37 ]
 [ 0.174  0.843 -0.508]
 [-0.35  -0.771 -0.532]
 [ 0.73   0.494  0.473]
 [-0.521  0.093 -0.848]
 [ 0.977 -0.004 -0.214]
 [ 0.444 -0.126 -0.887]
 [ 0.921  0.149 -0.361]
 [-0.656  0.301 -0.692]
 [ 0.081  0.978  0.194]
 [ 0.209  0.733  0.647]
 [-0.678 -0.206 -0.706]
 [-0.603  0.796  0.053]
 [-0.434  0.744  0.507]
 [ 0.891  0.096  0.443]
 [-0.362 -0.409 -0.838]
 [-0.366  0.907 -0.209]
 [ 0.478  0.149 -0.865]
 [-0.565 -0.726 -0.393]
 [-0.589 -0.123 -0.799]
 [-0.247  0.607  0.755]
 [ 0.356 -0.043 -0.933]
 [-0.043 -0.882 -0.47 ]
 [ 0.128  0.589 -0.798]
 [ 0.73   0.494 -0.473]
 [ 0.2   -0.267 -0.943]
 [ 0.321 -0.343 -0.883]
 [-0.652 -0.758 -0.013]
 [-0.926  0.033  0.375]
 [ 0.866 -0.043  0.499]
 [ 0.572  0.388  0.722]
 [-0.377 -0.613  0.695]
 [ 0.114 -0.005 -0.993]
 [ 0.335 -0.917 -0.218]
 [ 0.161  0.135  0.978]
 [ 0.058 -0.75  

(3) For the 100 vectors with a norm of 1 obtained in (2), compute a matrix of shape (100, 6) by stacking the original 100 vectors and their -1 multiplied counterparts **horizontally**, without changing the order of the vectors.

In [20]:
# (3)
C = np.concatenate([B_normalized, -B_normalized], axis=1)
print(C)

[[ 0.732 -0.564  0.384 -0.732  0.564 -0.384]
 [ 0.712 -0.624  0.323 -0.712  0.624 -0.323]
 [-0.043 -0.213  0.976  0.043  0.213 -0.976]
 [-0.177 -0.977 -0.122  0.177  0.977  0.122]
 [ 0.207 -0.4   -0.893 -0.207  0.4    0.893]
 [-0.028 -0.558  0.83   0.028  0.558 -0.83 ]
 [-0.092 -0.925  0.37   0.092  0.925 -0.37 ]
 [ 0.174  0.843 -0.508 -0.174 -0.843  0.508]
 [-0.35  -0.771 -0.532  0.35   0.771  0.532]
 [ 0.73   0.494  0.473 -0.73  -0.494 -0.473]
 [-0.521  0.093 -0.848  0.521 -0.093  0.848]
 [ 0.977 -0.004 -0.214 -0.977  0.004  0.214]
 [ 0.444 -0.126 -0.887 -0.444  0.126  0.887]
 [ 0.921  0.149 -0.361 -0.921 -0.149  0.361]
 [-0.656  0.301 -0.692  0.656 -0.301  0.692]
 [ 0.081  0.978  0.194 -0.081 -0.978 -0.194]
 [ 0.209  0.733  0.647 -0.209 -0.733 -0.647]
 [-0.678 -0.206 -0.706  0.678  0.206  0.706]
 [-0.603  0.796  0.053  0.603 -0.796 -0.053]
 [-0.434  0.744  0.507  0.434 -0.744 -0.507]
 [ 0.891  0.096  0.443 -0.891 -0.096 -0.443]
 [-0.362 -0.409 -0.838  0.362  0.409  0.838]
 [-0.366  

(4) (Somewhat Difficult)
Currently, in a 3D space, there are 8 quadrants numbered from 0 to 7. Instead of directly finding the quadrant, we will use 6 standard basis vectors and their inverse (6 vectors in total). The task is to find the "most similar" vector from this set.

After rotating the vectors, find the corresponding vector number and store it in a (100, 1) matrix.
(Hint: Think about how to assign the vector number using the normalized vectors. You can avoid using the inner product for efficiency. If you're unsure, try considering the case in 2D and then apply the same idea to 3D. You can utilize the normalization step from part (2).)

In [21]:
# (4)
C_argmax = np.argmax(C, axis=1).reshape(-1,1)
print(C_argmax)

[[0]
 [0]
 [2]
 [4]
 [5]
 [2]
 [4]
 [1]
 [4]
 [0]
 [5]
 [0]
 [5]
 [0]
 [5]
 [1]
 [1]
 [5]
 [1]
 [1]
 [0]
 [5]
 [1]
 [5]
 [4]
 [5]
 [2]
 [5]
 [4]
 [5]
 [0]
 [5]
 [5]
 [4]
 [3]
 [0]
 [2]
 [2]
 [5]
 [4]
 [2]
 [4]
 [4]
 [0]
 [3]
 [3]
 [4]
 [4]
 [2]
 [1]
 [5]
 [5]
 [4]
 [4]
 [2]
 [4]
 [2]
 [5]
 [3]
 [2]
 [0]
 [4]
 [1]
 [1]
 [2]
 [3]
 [4]
 [0]
 [2]
 [0]
 [0]
 [3]
 [1]
 [1]
 [4]
 [1]
 [2]
 [3]
 [0]
 [3]
 [0]
 [1]
 [4]
 [3]
 [5]
 [2]
 [3]
 [0]
 [0]
 [1]
 [3]
 [1]
 [3]
 [5]
 [4]
 [1]
 [3]
 [5]
 [2]
 [5]]


The 100 integers obtained here will be the values assigned to 100 vectors.

(5) (For those with extra time)
For the 100 vectors, calculate the cosine of the angle $\theta$ between every pair of vectors. Verify that vectors that are "similar" (i.e., have a small angle between them) are likely to have been assigned the same integer value, while vectors that are "dissimilar" (i.e., have a large angle between them) are likely to have been assigned different integer values.

In [22]:
# (5)
D = B_normalized
D_num = C_argmax

#Setting a threshold for cosine similarity to determine similarity.
threshold = 1 / np.sqrt(2)

n_similar = 0           # Number of similar vectors
n_similar_same = 0      # Number of similar vectors with the same index
n_notsimilar = 0        # Number of dissimilar vectors
n_notsimilar_dif = 0    # Number of dissimilar vectors with different indices
for i in range(100):
    for j in range(i+1,100):
        cos = np.dot(D[i],D[j]) / (LA.norm(D[i]) * LA.norm(D[j]))
        # Similar vectors
        if cos > threshold:
            n_similar += 1
            if D_num[i] == D_num[j]:
                n_similar_same += 1
        # Dissimilr vectors
        else:
            n_notsimilar += 1
            if D_num[i] != D_num[j]:
                n_notsimilar_dif += 1

print('Proportion of similar vectors with the same integer value assigned: ', n_similar_same / n_similar)
print('Proportion of dissimilar vectors with different integer values assigned]: ', n_notsimilar_dif / n_notsimilar)

Proportion of similar vectors with the same integer value assigned:  0.5973451327433629
Proportion of dissimilar vectors with different integer values assigned]:  0.9075374531835206
